# $FreeBSD$

PORTNAME=	litehtml
PORTVERSION=	0.5
DISTVERSIONPREFIX=	v
CATEGORIES=	www devel

MAINTAINER=	c0rn@o2.pl
COMMENT=	Fast and lightweight HTML/CSS rendering engine

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

#LIB_DEPENDS=	libgumbo.so:devel/gumbo

USES=		cmake ninja

USE_GITHUB=	yes

.include <bsd.port.mk>
